Repository 1anakin20/ComputerSquadBot, pull requests merged in 2020-10, with the labels that each got.

#33 Removed the weekDays enum and used the java provided one DayOfWeek
  src/main/java/com/computer_squad/ComputerSquadBot.java
  src/main/java/com/computer_squad/command/utilities/class_alarm/ClassAlarm.java
  src/main/java/com/computer_squad/command/utilities/class_alarm/Clock.java
  src/main/java/com/computer_squad/command/utilities/class_alarm/CronHelper.java
Labels: refactor

#36 Add an #number if there is an alarm with the same name
  src/main/java/com/computer_squad/command/utilities/class_alarm/ClassAlarm.java
  src/main/java/com/computer_squad/command/utilities/class_alarm/Clock.java
Labels: enhancement

#41 Loads the alarms back at the beginning
  src/main/java/com/computer_squad/command/utilities/class_alarm/Clock.java
  src/main/java/com/computer_squad/command/utilities/class_alarm/JSONAlarms.java
  src/main/java/com/computer_squad/services/UserEvents.java
Labels: enhancement

#43 Delete the alarm from the json file when removed
  src/main/java/com/computer_squad/command/utilities/class_alarm/Clock.java
  src/main/java/com/computer_squad/command/utilities/class_alarm/JSONAlarms.java
Labels: bug

#40 Removed templates for issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#38 Flip command to choose between two options
  src/main/java/com/computer_squad/ComputerSquadBot.java
  src/main/java/com/computer_squad/command/fun/flip/Flip.java
Labels: enhancement

#44 Fixed exception thrown when there aren't 2 options
  src/main/java/com/computer_squad/command/fun/flip/Flip.java
Labels: bug

#45 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#51 Replaced old configuration information with the new one
  README.md
Labels: documentation

#53 Change argument: new to add
  src/main/java/com/computer_squad/command/utilities/class_alarm/ClassAlarm.java
Labels: enhancement, hacktoberfest-accepted
